const array=[1,4,3,7,6,5];
//console.log(array);
//console.log(array[0]);
//console.log(array.length);
let array2=[5,8,"renu",true];
//console.log(array.concat(array2));
array.push(9);
//console.log(array);
array.unshift(2);
//console.log(array);
array.pop();
//console.log(array);
array.shift();
//console.log(array);
const myarr=new Array(2,4,6,8,10);
//console.log(myarr.indexOf(2));
//console.log(myarr.includes(1));
//const newarr=myarr.join();
//console.log(newarr);
//console.log(myarr);
let slice=myarr.slice(0,3);
//console.log(slice);
slice=myarr.slice(1,4);
//console.log(slice);
let splice=myarr.splice(0,2);
//console.log(splice);
//console.log(myarr);
const marvel_heros=["ironman","thor","hulk","captain america"];
const dc_heros=["superman","batman","flash"];
const all_heros=marvel_heros.concat(dc_heros);
//console.log(all_heros);
marvel_heros.push(dc_heros);
//console.log(marvel_heros);
//console.log(marvel_heros[4][2]);
const new_heros=[...marvel_heros,...dc_heros];
console.log(new_heros);
const marvel = ["ironman", "thor"];
const dc = ["batman", "flash"];

const all = [...marvel, ...dc];
console.log(all);

const another_array=[1,2,[4,3,2],7,8,[9,10,3],6];
console.log(another_array.flat());
console.log(Array.isArray("renuka"));
console.log(Array.from("renuka"));
let score1=100;
let score2=200;
let score3=300;
console.log(Array.of(score1,score2,score3));